# Generated by Django 4.0.1 on 2022-01-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_doctors_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='doctor',
            new_name='clinic',
        ),
    ]
