# Generated by Django 4.0.1 on 2022-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_clinic_closing_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='opening_days',
        ),
        migrations.AddField(
            model_name='clinic',
            name='opening_days',
            field=models.ManyToManyField(to='health.Day'),
        ),
    ]
