# Generated by Django 4.0.1 on 2022-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_remove_clinic_opening_days_clinic_opening_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='opening_days',
        ),
        migrations.AddField(
            model_name='clinic',
            name='opening_days',
            field=models.ManyToManyField(to='health.Day'),
        ),
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], max_length=10, null=True),
        ),
    ]
