# Generated by Django 4.0.1 on 2022-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[(0, 'monday'), (1, 'sunday')], max_length=50, null=True),
        ),
    ]
