# Generated by Django 4.0.1 on 2022-02-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('sunday', 0), ('monday', 1)], max_length=50, null=True),
        ),
    ]
