# Generated by Django 4.0.1 on 2022-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday')], max_length=10, null=True),
        ),
    ]
