# Generated by Django 4.0.1 on 2022-02-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_alter_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='opening_days',
        ),
        migrations.RemoveField(
            model_name='day',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.clinic'),
        ),
        migrations.AddField(
            model_name='day',
            name='opening_day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'د.شنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=10, null=True),
        ),
    ]
