# Generated by Django 4.0.1 on 2022-02-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_remove_clinic_closing_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='doctor',
            field=models.ManyToManyField(to='health.Doctor'),
        ),
    ]
