# Generated by Django 4.0.1 on 2022-02-18 18:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_blog_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
