# Generated by Django 4.0.1 on 2022-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0025_rename_email_comment_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fullname',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
