# Generated by Django 4.0.1 on 2022-02-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0027_alter_comment_e_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('top_img', models.ImageField(upload_to='img')),
                ('phone', models.CharField(max_length=15, null=True)),
                ('Address', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='clinic_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.clinic_info'),
        ),
    ]
