# Generated by Django 4.0.1 on 2022-02-20 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0028_clinic_info_day_clinic_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
