# Generated by Django 4.0.1 on 2022-02-20 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_clinic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='description_head',
            field=ckeditor.fields.RichTextField(max_length=50, null=True),
        ),
    ]
