# Generated by Django 4.0.1 on 2022-02-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0030_clinic_description_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_info',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='clinic_info',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clinic_info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clinic_info',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clinic_info',
            name='top_img',
        ),
        migrations.RemoveField(
            model_name='day',
            name='clinic_info',
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='clinic_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='health.clinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='slider_img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
