# Generated by Django 4.0.1 on 2022-02-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0031_remove_clinic_info_address_remove_clinic_info_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic_info',
            name='clinic_ptr',
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.day'),
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.hours'),
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='top_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
