# Generated by Django 4.0.1 on 2022-02-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0033_remove_clinic_info_hour_clinic_info_closing_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic_info',
            old_name='day',
            new_name='end_day',
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='star_day',
            field=models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'د.شنبه'), ('دوشنبه', 'دوشنبه'), ('سه شنبه', 'سه شنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=10, null=True),
        ),
    ]
