# Generated by Django 4.0.1 on 2022-02-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0035_alter_clinic_info_closing_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_info',
            name='address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clinic_info',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
